### ISSUE TITLE
Drop Python 2

### ISSUE THREAD

**Issue by untitaker** [geier/khal#302]
OS/Distributions readiness to support python 3 only applications
===================

* :white_check_mark: Arch
* :white_check_mark: Fedora
*  :x:FreeBSD (no pre-build package available any more)
* :white_check_mark:: NetBSD/pkg.src 
* :question: openSUSE
* :white_check_mark: Debian/Ubuntu: there is no package anyway, but otherwise does look ready
* :white_check_mark: Gentoo
* what other (major) distributions/OSes are missing from this list?

**Feel free to edit this**

**Comment by geier** [comment]
For me FreeBSD not bringing python 3 packages by default is a major blocker on this.

**Comment by hobarrera** [comment]
For the record, this is a non-issue on Arch, since we're already using py3 (which is the default).

**Comment by hobarrera** [comment]
Debian is only missing `python3-tzlocal`, but has the rest of the dependency tree. Then again, Debian is also missing `python-tzlocal`, so there's not loss there.

This also means that all its downstream distros should have the necessary dependencies too (or can be ported with minimal effort).

I'm pointing this out because Debian is a very useful reference of where conservative distributions are standing.

For users using pip, this makes no difference.

**Comment by mbaldessari** [comment]
For the record, in Fedora land we should also be good for this change

**Comment by hobarrera** [comment]
It looks like there's no opposition to dropping python2.
How do you feel about setting an "end date" for this discussion, and, should not objections arise, go ahead and start looking at #304?
Maybe give this discussion a max-lifetime of 2 weeks?

**Comment by geier** [comment]
We are going to loose pre-build packages on FreeBSD at least, so I'd like some time to think about it (but two weeks is fine).

**Comment by hobarrera** [comment]
What exactly does "not bringing python 3 packages by default" mean? That python3 is not part of the base system? Or it's not even a binary package?

**Comment by geier** [comment]
OS/Distributions readiness to support python 3 only applications
===================

*  :white_check_mark: Arch
* :white_check_mark: Fedora
*  :x:FreeBSD (no pre-build package available any more)
* :question: NetBSD/pkg.src 
* :question: openSUSE
* :white_check_mark: Debian/Ubuntu there is no package anyway, but otherwise does look ready
* what other (major) distributions/OSes are missing from this list?

**Feel free to edit this**

@untitaker would you mind if I edited your top post?

**Comment by geier** [comment]
regarding the situtation on FreeBSD: there is python 3 is available in the port system (and pre build as a package) in nearly all flavors (3.2, 3.3, 3.4 and 3.5). Pre build packages for khal will not be available anymore (until they change the build system to build ports for different python versions at the same time, which should be *fixed eventually (since a few years)*). But one *should* be able to build the port oneself (I'm currently testing this).

**Comment by hobarrera** [comment]
> until they change the build system to build ports for different python versions at the same time

We wouldn't want different python versions at the same time; only a python3 version of this package. Is this also impossible?

**Comment by geier** [comment]
@hobarrera yes, (nearly) all pre-build packages must use the same python version.

**Comment by geier** [comment]
@0-wiz-0 what is the situation for python 3 only applications with pkg.src?

**Comment by lkraav** [comment]
Gentoo is an easy green checkmark.

**Comment by 0-wiz-0** [comment]
pkgsrc already builds binary packages for khal for all supported python versions (currently 27 33 34) so no problem here.

**Comment by untitaker** [comment]
Sure you can edit the OP why not

On 30 November 2015 16:48:16 CET, Thomas Klausner <notifications@github.com> wrote:
>pkgsrc already builds binary packages for khal for all supported python
>versions (currently 27 33 34) so no problem here.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/geier/khal/issues/302#issuecomment-160667478

-- 
Sent from my phone. Please excuse my brevity.
