### ISSUE TITLE
Create config file if it doesn't exist

### ISSUE THREAD

**Issue by nodiscc** [geier/khal#55]
Maybe hardcode the default config in the main script, and create `~/.config/khal/khal.conf` if it is unreadble

**Comment by untitaker** [comment]
I think this might now be easier with the included scheme file.

**Comment by johannes-darms** [comment]
Would copying the sample config from source to the desired location sufficient enough? If it is, I would volunteer :) Maybe with a small dialog? Like "No Configuration detected. Should the configuration file created with defaults? (Y)es (N)o"

**Comment by geier** [comment]
I think this would be good enough (and a dialog is probably a good idea
as well). And perhaps create the directory of the calendar as well.

Quoting Johannes Darms (2015-09-24 14:58:03)

**Comment by untitaker** [comment]
We would have to move the example config from the repo root inside the `khal`-folder.

**Comment by lucc** [comment]
Copying the default config file might be difficult because we might not know where it is. If you run khal from the git repository we know where it is but I installed khal from the AUR on Arch Linux and the example config was installed to `/usr/share/doc/khal/examples/khal.conf` but I can just as well imagine that it would be in some other place or not installed at all.

So it might be easier to write to default config out from the program. But in this case (the defaults being hard coded into the program) khal could just run with the default settings if no config file was found.
